variable "global_prefix" {}
variable "temp_bucket_name" {}
variable "repository_bucket_name" {}
variable "website_bucket_name" {}
variable "aws_account_id" {}
variable "aws_region" {}
variable "environment_type" {}
variable "services_url" {}
variable "services_auth_type" {}
variable "services_auth_context" {}
