import * as AWS from "aws-sdk";
import { AIJob, EnvironmentVariables, McmaException, ProblemDetail } from "@mcma/core";
import { getTableName } from "@mcma/data";
import { ProcessJobAssignmentHelper, ProviderCollection, WorkerRequest } from "@mcma/worker";
import { AwsS3FileLocator, AwsS3FileLocatorProperties, AwsS3FolderLocatorProperties } from "@mcma/aws-s3";

const S3 = new AWS.S3();
const Polly = new AWS.Polly();
const environmentVariables = EnvironmentVariables.getInstance();

export async function textToSpeech(providers: ProviderCollection, jobAssignmentHelper: ProcessJobAssignmentHelper<AIJob>) {
    const logger = jobAssignmentHelper.logger;

    const jobInput = jobAssignmentHelper.jobInput;
    const inputFile = jobInput.get<AwsS3FileLocatorProperties>("inputFile");
    const voiceId = jobInput.voiceId;
    const jobAssignmentDatabaseId = jobAssignmentHelper.jobAssignmentDatabaseId;

    logger.debug("12. Generate speech from translation text");

    logger.debug("12.1. get input text file from translation service output");
    // get input text file from translation service
    const s3Bucket = inputFile.bucket;
    const s3Key = inputFile.key;
    let s3Object;
    try {
        s3Object = await S3.getObject({
            Bucket: s3Bucket,
            Key: s3Key,
        }).promise();
    } catch (error) {
        throw new McmaException("Unable to read file in bucket '" + s3Bucket + "' with key '" + s3Key + "' due to error: " + error.message);
    }

    logger.debug("12.2. extract text from file");
    const inputText = s3Object.Body.toString();
    logger.debug(inputText);

    logger.debug("12.3. configure and call text to speech service");
    const params = {
        OutputFormat: "mp3",
        OutputS3BucketName: environmentVariables.get("ServiceOutputBucket"),
        OutputS3KeyPrefix: "TextToSpeechJob-" + jobAssignmentDatabaseId.substring(jobAssignmentDatabaseId.lastIndexOf("/") + 1),
        Text: inputText,
        VoiceId: voiceId,
        SampleRate: "22050",
        TextType: "text"
    };
    const data = await Polly.startSpeechSynthesisTask(params).promise();

    logger.debug("12.4. visualise data containing the url of the mp3 generated by the service");
    logger.debug(JSON.stringify(data, null, 2));

    logger.debug("12.5. OutputS3KeyPrefix used in s3-trigger");
    logger.debug("See regex for textToSpeechJob in aws-ai-service/se-trigger/src/index.js");
    logger.debug(params.OutputS3KeyPrefix);
}

export async function processTextToSpeechJobResult(providers: ProviderCollection, workerRequest: WorkerRequest) {
    const jobAssignmentHelper = new ProcessJobAssignmentHelper(
        await providers.dbTableProvider.get(getTableName(environmentVariables)),
        providers.resourceManagerProvider.get(environmentVariables),
        workerRequest
    );

    const logger = jobAssignmentHelper.logger;

    try {
        await jobAssignmentHelper.initialize();
        logger.debug("12.6. Retrieve job inputParameters");
        let jobInput = jobAssignmentHelper.jobInput;

        logger.debug("12.7. Copy textToSpeech output file to output location");
        let copySource = encodeURI(workerRequest.input.outputFile.bucket + "/" + workerRequest.input.outputFile.key);
        let outputLocation = jobInput.get<AwsS3FolderLocatorProperties>("outputLocation");
        let s3Bucket = outputLocation.bucket;
        // define the output file name of the mp3 file
        let s3Key = (outputLocation.keyPrefix ? outputLocation.keyPrefix : "") + "translation.mp3";

        try {
            await S3.copyObject({
                CopySource: copySource,
                Bucket: s3Bucket,
                Key: s3Key,
            }).promise();
        } catch (error) {
            throw new McmaException("Unable to copy output file to bucket '" + s3Bucket + "' with key '" + s3Key + "' due to error: " + error.message);
        }

        logger.debug("12.8. updating JobAssignment with jobOutput");
        jobAssignmentHelper.jobOutput.set("outputFile", new AwsS3FileLocator({
            bucket: s3Bucket,
            key: s3Key
        }));

        await jobAssignmentHelper.complete();
    } catch (error) {
        logger.error(error.toString());
        try {
            await jobAssignmentHelper.fail(new ProblemDetail({
                type: "uri://mcma.ebu.ch/rfc7807/aws-ai-service/generic-failure",
                title: "Generic failure",
                detail: error.message
            }));
        } catch (error) {
            logger.error(error.toString());
        }
    }

    logger.debug("12.10. Cleanup: Deleting original output file from service");
    try {
        await S3.deleteObject({
            Bucket: workerRequest.input.outputFile.bucket,
            Key: workerRequest.input.outputFile.key,
        }).promise();
    } catch (error) {
        logger.warn("Failed to cleanup transcribe output file");
    }
}
